{...}: {
  homebrew = {
    taps = [
      # "homebrew/cask-fonts"
    ];
    enable = false;
    onActivation.autoUpdate = true;
    onActivation.upgrade = true;
    casks = [
      # "aerospace"
      "homerow"
      "chatgpt"
      "spotify"
      "claude-code"
      "codex"
      "discord"
      "raycast"
      "bambu-studio"
      # "blender"
      # "vlc"
      # "folx"
      # "forklift"
      "helium-browser"
      "kitty"
      "karabiner-elements"
      "mongodb-compass"
      "ngrok"
      "nosql-workbench"
      # "opera-gx"
      "rar"
      "soapui"
      "stats"
      "spaceid"
      "studio-3t"
      # "ultimaker-cura"
      # "visual-studio-code"
      # "vivaldi"
      # "warp"
      # "whatsapp"
      # "wezterm"
      "zed"
      "zen"
      "glow"
      "k9s"
      "mermaid-cli"
      # "zen-browser"
      # "font-monaspace-nerd-font"
      "font-monaspice-nerd-font"
      "font-noto-sans-symbols-2"
      "font-mononoki-nerd-font"
      "hammerspoon"
      # "obs"
      "orbstack"
      # "oso-cloud"
      "zulu@17"
      "jackielii/tap/skhd-zig"
      "drewzemke/tap/tongo"
      "insomnia"
      "slack"
    ];
  };
}
