{...}: {
  homebrew = {
    taps = [
      "darrylmorley/whatcable"
      "drewzemke/tap"
      "fcoury/tap"
      "jackielii/tap"
      "modem-dev/tap"
      "normen/tap"
      "riii111/sabiql"
      "y3owk1n/tap"
    ];
    enable = false;
    onActivation.autoUpdate = true;
    onActivation.upgrade = true;
    brews = [
      "cocoapods"
      "difftastic"
      "drewzemke/tap/tongo"
      "e2fsprogs"
      "fcoury/tap/tsql"
      "glab"
      "glow"
      "graphviz"
      "herdr"
      "jackielii/tap/skhd-zig"
      "k9s"
      "mermaid-cli"
      "modem-dev/tap/hunk"
      "mongosh"
      "mtools"
      "normen/tap/whatscli"
      "opencode"
      "sabiql"
      "superfile"
      "terminal-notifier"
      "u-boot-tools"
    ];
    casks = [
      # "aerospace"
      "homerow"
      "folx"
      "chatgpt"
      "spotify"
      "claude-code@latest"
      "codex"
      "discord"
      "raycast"
      "bambu-studio"
      "blender"
      # "vlc"
      # "folx"
      # "forklift"
      "helium-browser"
      "kitty"
      "karabiner-elements"
      "mongodb-compass"
      "ngrok"
      "nosql-workbench"
      # "opera-gx"
      "rar"
      "soapui"
      "stats"
      "spaceid"
      "studio-3t"
      # "ultimaker-cura"
      # "visual-studio-code"
      # "vivaldi"
      # "warp"
      # "whatsapp"
      # "wezterm"
      "zed"
      "zen"
      # "zen-browser"
      # "font-monaspace-nerd-font"
      "font-monaspice-nerd-font"
      "font-noto-sans-symbols-2"
      "font-mononoki-nerd-font"
      "hammerspoon"
      # "obs"
      "orbstack"
      # "oso-cloud"
      "zulu@17"
      "insomnia"
      "slack"
      "steam"
      "t3-code@nightly"
      "darrylmorley/whatcable/whatcable"
      "y3owk1n/tap/neru-nightly"
    ];
  };
}
